'use client';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { usePathname } from "next/navigation";
import Sidebar from "@/components/sidebar";
import { UserProvider } from "@/Context/UserContext";
import { Toaster } from "sonner";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const pathname = usePathname()

  const noSidebarRoutes = ['/login', '/register', '/verify-email']

  const showSidebar = !noSidebarRoutes.includes(pathname)

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}      >
      <UserProvider>
        {showSidebar && <Sidebar />}
        <section className="flex-1">{children}</section>
        <Toaster richColors position="bottom-center"/>
        </UserProvider>

      </body>
    </html>
  )
}