version: '3.8'

services:
  backend:
    build:
      context: ./ProgbattleBackend
    container_name: backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./ProgbattleBackend:/app
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./ProgbattleBackend/.env
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
